"""Tests for Rapid Fire Inquiry Limiter — auto-generated by SUSHILOOP."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent / 'skills'))
from rapid_fire_inquiry_limiter import rapid_fire_inquiry_limiter

EDGE_INPUTS = ["", "   ", "a", "hello", "no punct here", None, "12345", "\n\n"]

def test_returns_dict_on_all_edges():
    for inp in EDGE_INPUTS:
        out = rapid_fire_inquiry_limiter(inp)
        assert isinstance(out, dict), f"non-dict on {inp!r}"
        assert "blocked" in out and "confidence" in out, f"missing keys on {inp!r}"

def test_confidence_in_range():
    for inp in EDGE_INPUTS:
        c = rapid_fire_inquiry_limiter(inp).get("confidence")
        assert isinstance(c, (int, float)) and 0.0 <= c <= 1.0
