"""Tests for Temporal Context Validator — auto-generated by SUSHILOOP."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent / 'skills'))
from temporal_context_validator import temporal_context_validator

EDGE_INPUTS = ["", "   ", "a", "hello", "no punct here", None, "12345", "\n\n"]

def test_returns_dict_on_all_edges():
    for inp in EDGE_INPUTS:
        out = temporal_context_validator(inp)
        assert isinstance(out, dict), f"non-dict on {inp!r}"
        assert "blocked" in out and "confidence" in out, f"missing keys on {inp!r}"

def test_confidence_in_range():
    for inp in EDGE_INPUTS:
        c = temporal_context_validator(inp).get("confidence")
        assert isinstance(c, (int, float)) and 0.0 <= c <= 1.0
